name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install packages
        run: npm install

      - name: Check files exist
        run: |
          test -f server.js && echo "✅ server.js found"
          test -f package.json && echo "✅ package.json found"
          test -d src && echo "✅ src folder found"

      - name: Check syntax
        run: node -c server.js

      - name: Success!
        run: echo "🎉 All checks passed!"
